version: '3.8'

services:
  backend:
    build:
      context: ./projet-ebanking-ebankingSecuredDev/projet-ebanking-ebankingSecuredDev #
    container_name: ebanking-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres.c0x6q2u2yn60.us-east-1.rds.amazonaws.com:5432/ebanking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123
    ports:
      - "8080:8080"
    restart: on-failure

  frontend:
    build:
      context: ./projet-ebanking-EbankingDevFront/projet-ebanking-EbankingDevFront
    container_name: ebanking-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: on-failure

  frontend-admin:
    build:
      context: ./projet-ebanking-admin-front/projet-ebanking-admin-front #
    container_name: ebanking-frontend-admin
    ports:
      - "81:80"
    depends_on:
      - backend
    restart: on-failure
