jwt.secret=boG0VojP3kc2uXw5fzEVpGWGGhjh0yobw98ROjY5xiY=
jwt.expiration=300000
jwt.issuer=http://localhost:8080
jwt.audience=http://localhost:4200
jwt.refresh-token.expiration=86400000
isDevEnvironment=true